import jsPDF from 'jspdf';
import type { TripFormData, DayPlan } from '../types';

export async function generateItineraryPDF(
  tripData: TripFormData,
  dayPlans: DayPlan[]
): Promise<void> {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  const addNewPageIfNeeded = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }
  };

  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('TripRhythm Itinerary', margin, yPosition);
  yPosition += 15;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Destination: ${tripData.destination}`, margin, yPosition);
  yPosition += 7;
  pdf.text(`Start Date: ${tripData.start_date}`, margin, yPosition);
  yPosition += 7;
  pdf.text(`Duration: ${tripData.days} days`, margin, yPosition);
  yPosition += 7;
  pdf.text(`Travel Style: ${tripData.travel_style}`, margin, yPosition);
  yPosition += 7;
  pdf.text(`Walking Tolerance: ${tripData.walking_tolerance}`, margin, yPosition);
  yPosition += 7;
  pdf.text(`Wake Time: ${tripData.wake_time} | Sleep Time: ${tripData.sleep_time}`, margin, yPosition);
  yPosition += 15;

  dayPlans.forEach((day, dayIndex) => {
    addNewPageIfNeeded(30);

    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Day ${dayIndex + 1} - ${day.date}`, margin, yPosition);
    yPosition += 8;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    const summaryLines = pdf.splitTextToSize(day.summary, pageWidth - 2 * margin);
    summaryLines.forEach((line: string) => {
      addNewPageIfNeeded(6);
      pdf.text(line, margin, yPosition);
      yPosition += 5;
    });
    yPosition += 8;

    day.activities.forEach((activity) => {
      addNewPageIfNeeded(20);

      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${activity.time} - ${activity.name}`, margin, yPosition);
      yPosition += 6;

      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      const descLines = pdf.splitTextToSize(activity.description, pageWidth - 2 * margin - 5);
      descLines.forEach((line: string) => {
        addNewPageIfNeeded(5);
        pdf.text(line, margin + 5, yPosition);
        yPosition += 4;
      });

      pdf.setFont('helvetica', 'italic');
      pdf.text(`Effort Level: ${activity.effortLevel}`, margin + 5, yPosition);
      yPosition += 8;
    });

    yPosition += 5;
  });

  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'italic');
  const footerText = 'Generated by TripRhythm - Your AI Travel Planner';
  const footerWidth = pdf.getTextWidth(footerText);
  pdf.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);

  const filename = `TripRhythm-${tripData.destination.replace(/\s+/g, '-')}-${tripData.start_date}.pdf`;
  pdf.save(filename);
}
